#!/usr/bin/env python

import sys

from gui.rqt_iris import MyPlugin
from gui.step import StepPlugin
from rqt_gui.main import Main

plugin = 'gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
